# Generated by Django 2.2.3 on 2019-07-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vilao',
            name='armas',
            field=models.CharField(choices=[('machado', 'Machado'), ('escada', 'Escada'), ('espada', 'Espada'), ('veneno', 'Veneno'), ('pexera', 'Pexera'), ('serra elétrica', 'Serra Elétrica'), ('punhos', 'Punhos'), ('ak47', 'AK47'), ('almofada', 'Almofada'), ('outros', 'Outros'), ('desarmado', 'Desarmado')], max_length=20),
        ),
    ]
